name: Template

on:
  workflow_call:
    secrets:
      ENV:
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ secrets.ENV }}
    steps:
    - run: |
        if [[ "${{ secrets.ENV }}" == "dev" ]]
        then
          echo hi
        fi

        if [[ "${{ secrets.ENV }}" == "workflow" ]]
        then
          echo bye
        fi

        echo ${{ secrets.ENV }}
