name: Template

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      SOMETHING:
        required: true
        type: string
    secrets:
      NAME:
        required: true
jobs:
    # runs-on: ubuntu-latest
    # environment: ${{ inputs.ENV }}
    # steps:
    # - run: |
    #     # if [[ "${{ secrets.NAME }}" == "dev" ]]
    #     # then
    #     #   echo deone
    #     # fi

    #     # if [[ "${{ secrets.NAME }}" == "workflow" ]]
    #     # then
    #     #   echo stone
    #     # fi

    #     # echo ${{ secrets.NAME }}

    #     echo ${{ inputs.ENV }}
  echo:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.SOMETHING }}-${{ inputs.ENV }}