name: Template

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    steps:
    - run: |
        if [[ "${{ secrets.NAME }}" == "dev" ]]
        then
          echo hi
        fi

        if [[ "${{ secrets.NAME }}" == "workflow" ]]
        then
          echo bye
        fi

        echo ${{ matrix.environments }}
