name: Template

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      SOMETHING:
        required: true
        type: string
    secrets:
      EDWIN:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    steps:
    - run: |
        if [[ "${{ secrets.NAME }}" == "dev" ]]
        then
          echo deone
        fi

        if [[ "${{ secrets.EDWIN }}" == "cool" ]]
        then
          echo stone
        fi

  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: echo ${{ secrets.EDWIN }}